CREATE TABLE orders (
    id CHAR(36) NOT NULL DEFAULT (UUID()),
    status VARCHAR(255) NOT NULL DEFAULT 'pending',
    total_amount INT(11) NOT NULL,
    transaction_token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);
