CREATE TABLE products (
    id CHAR(36) NOT NULL DEFAULT UUID(),
    name VARCHAR(255) NOT NULL,
    price INT(11) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP(),
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
    PRIMARY KEY (id)
);
